[project]
authors = [{ "name" = "Volodymyr Pivoshenko", "email" = "contact@pivoshenko.dev" }]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Other Environment",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = []
description = "A lightweight package with zero runtime dependencies for converting Markdown into Steam-compatible markup, and back again."
keywords = [
  "bbcode",
  "converter",
  "formatter",
  "gaming",
  "markdown",
  "markup",
  "parser",
  "steam",
  "steam-bbcode",
  "steam-bbcode-converter",
  "steam-workshop",
  "steamify",
  "text-processing"
]
license = "MIT"
maintainers = [{ "name" = "Volodymyr Pivoshenko", "email" = "contact@pivoshenko.dev" }]
name = "steamify"
readme = "README.md"
requires-python = ">=3.10"
version = "2.0.1"

[project.urls]
Homepage = "https://github.com/pivoshenko/steamify"
Repository = "https://github.com/pivoshenko/steamify"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
formatters = ["pyupgrade~=3.21.2", "ruff~=0.16.7"]
linters = ["ruff~=0.16.7", "ty~=0.0.80"]
tests = ["coverage[toml]~=7.16.0", "pytest~=9.1.1", "pytest-cov~=7.1.0", "pytest-mock~=3.15.1", "pytest-sugar~=1.1.1"]

[tool.coverage.run]
omit = ["*/__init__.py"]

[tool.pytest.ini_options]
addopts = ["--color=yes", "--cov=src", "--cov-report=term-missing"]
testpaths = ["tests"]

[tool.ruff]
fix = true
line-length = 100
unsafe-fixes = true

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"

[tool.ruff.lint]
ignore = ["COM812", "CPY001", "D102", "D103", "D203", "D212"]
select = ["ALL"]

[tool.ruff.lint.isort]
force-single-line = true
from-first = false
length-sort-straight = true
lines-after-imports = 2
lines-between-types = 1
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["INP001", "S101"]
